name = "mind-frontend"
pages_build_output_dir = "dist/mind-frontend/browser"
compatibility_date = "2025-12-03"
[build]
command = "npm run build"
watch_dir = [
  "src",
  "public",
  "angular.json",
  "package.json"
]

[assets]
directory = "dist/mind-frontend/browser"

[vars]
# Add runtime environment variables here, e.g.
# API_BASE_URL = "https://api.example.com"
