name = "mind-frontend"
compatibility_date = "2025-12-03"
pages_build_output_dir = "dist/mind-frontend/browser"
build_command = "npm run build"
pages_build_watch_dir = [
  "src",
  "angular.json",
  "package.json",
  "public"
]

[vars]
# Add runtime environment variables here, e.g.
# API_BASE_URL = "https://api.example.com"
